AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyExistingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: F3Lambda::F3Lambda.Function::FunctionHandler  # Your handler function
      Runtime: dotnet6  # Updated to .NET 6
      CodeUri: .  # Path to your code directory
      MemorySize: 128
      Timeout: 100
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /  # The API path you want to call
            Method: post  # HTTP method
