namespace F3Lambda.Tests
{
    public static class LambdaTestData
    {
        public static List<string> PaxNames = new List<string>
        {
            "DR",
            "QSource",
            "88",
            "Ponch",
            "Rapid",
            "Hall Pass",
            "Singlet",
            "Snoop",
            "KJV",
            "Tech Deck",
            "Psalty",
            "Foghorn",
            "MarkyMark",
            "Schwartz",
            "Banjo",
            "Horry",
            "Bartman",
            "Schmear",
            "LOL",
            "Chuck E.",
            "Fanny Pack",
            "Spirit Fingers",
            "Razzmatazz",
            "Happy Meal",
            "Bandwagon",
            "Offshore",
            "Thumper",
            "Birthday Suit",
            "Wow",
            "Purple Rain",
            "Pyro",
            "Baller",
            "Soft Kitty",
            "Double Stuff",
            "Toro",
            "Wall-E",
            "Smelt",
            "Jet Puffed",
            "Deep V",
            "Yoshi",
            "Herschel",
            "Pikachu",
            "Magellan",
            "Picard",
            "Polo",
            "Luigi",
            "Backseat",
            "Mudslide",
            "Mudpie",
            "Excitebike",
            "Sue",
            "Drumstick",
            "Samsonite",
            "Top 40",
            "Animal Style",
            "Jake from State Farm",
            "Miles",
            "Clove",
            "Al Davis",
            "Shrink",
            "Bog",
            "Peach",
            "Huggies",
            "Daisy",
            "LZ",
            "Bono",
            "Captain Hook",
            "Happy Tree",
            "Choo Choo",
            "Red Light",
            "Pixar",
            "Paperboy",
            "PonyTail",
            "Green Mile",
            "Potts",
            "Recall",
            "Cage Free",
            "Lambchops",
            "Hightower",
            "Mumbles",
            "Manny Pedi",
            "Green Thumb",
            "Stepbrother",
            "Turf Toe",
            "Kiddie Pool",
            "My Pleasure \"Inactive\"",
            "Slurpee",
            "Tuck",
            "Swisher",
            "Doubtfire",
            "Shout",
            "Fix it Felix",
            "Glass",
            "Metamucil",
            "Clark",
            "Sleeper Hold",
            "Sheets",
            "Amnesia",
            "Padre",
            "Bag Boy",
            "Fold-em",
            "Recovery",
            "51",
            "Chitwood",
            "Statute",
            "Carrot Top",
            "Good Game",
            "Gnome",
            "NoMar",
            "Coat Hanger",
            "Mr. Meanor",
            "Squeegy",
            "Ross",
            "Aloe Vera",
            "Angry Cub",
            "Shuck",
            "Spider",
            "Snot",
            "Suds",
            "D. Baiter",
            "Paperclip",
            "Skype",
            "Pinot",
            "Decline",
            "Hamm",
            "Gas Fight",
            "Double Dip",
            "Pizza!Pizza!",
            "Rat",
            "Jetset",
            "RoBlox",
            "Riggs",
            "Lip Sync",
            "Reborn",
            "Carlton",
            "Cardiac",
            "Snak Shak",
            "Kazoo",
            "Windsor",
            "Shakira",
            "Gretzky",
            "A.I.",
            "Dangle",
            "Dismount",
            "Gumby",
            "Wham-O",
            "Wipe Out",
            "Reject",
            "12th Man(sf)",
            "Blowout",
            "Like and Subscribe",
            "Goon",
            "Mixed Greens",
            "Blue Pill",
            "Sparkz",
            "Cutco",
            "Dude",
            "Outhouse",
            "Knott's Berry",
            "Twinkles",
            "Munchkin",
            "McGriddle",
            "Hard Pass",
            "Friendly Fire",
            "Pack Out",
            "Swat",
            "JimBob",
            "TuneUp",
            "Meat Pie",
            "Deuce",
            "Daddy Daycare",
            "Swap Meet",
            "Grilz",
            "Sleepy Head",
            "Impossi-hole",
            "Oscar",
            "Chippendale",
            "Happy Tree",
            "Betty Crocker",
            "Practice?",
            "De-Pantz'd",
            "Lil Oats",
            "Yard Sale",
            "Spread'em",
            "Homer",
            "Mo",
            "Fake News",
            "Destiny",
            "Jumpstart",
            "Leonardo",
            "Tron",
            "HotWire",
            "Bends",
            "S'mores",
            "Skittles",
            "HollaBack",
            "Baskinz",
            "Parking Brake",
            "Dil",
            "Scrappy Doo",
            "Fava",
            "Skiball",
            "Sofa King",
            "Chong",
            "Eh?",
            "Casi",
            "Auger",
            "Gallahad",
            "Butter Face",
            "Putt Putt",
            "Pi",
            "Toad",
            "Hundi",
            "Slice",
            "Moana",
            "Singe",
            "Showers",
            "Mouth Breather",
            "SharkBait",
            "Angry Orchard",
            "Nep",
            "Hasbro",
            "Almond Joy",
            "Woosh!",
            "Chops",
            "Pvt Parts",
            "U-Haul",
            "Quick Quack",
            "Pull-Ups",
            "U-Turn",
            "BBs",
            "Passport",
            "Crews",
            "Jigglypuff",
            "Knuckle Puck",
            "Piggy Toe",
            "Limited Exposure",
            "Veggie Tales",
            "Shooter",
            "Bangkok",
            "Pop Top",
            "Full Service",
            "OJ",
            "Gadget",
            "TikTok",
            "RoadRash",
            "Pinto",
            "Gump",
            "HeatCheck",
            "Toastmaster",
            "Spitwad",
            "Uncle Drew",
            "Char Char Binks",
            "New World",
            "Hannah Montana",
            "Ole'",
            "Crane",
            "Bubly",
            "Crockett",
            "DA",
            "OrderUp",
            "Thrifty",
            "SportySpice",
            "Chubbs",
            "GTL",
            "Final Destination",
            "Lost And Found",
            "Oven Mitt",
            "Linguini",
            "Chalupa",
            "M.I.C.",
            "Ranchero",
            "Bail Bonds",
            "TraLaLa",
            "Up Doug",
            "Vespa",
            "Boxers",
            "Bilbo",
            "Spork",
            "Burgundy",
            "Zelda",
            "Spidey",
            "Rollback",
            "Eraser",
            "Spot",
            "Rebound",
            "Supa-Star!",
            "Nutmeg",
            "Forked",
            "Basecamp",
            "Houdini",
            "Marv",
            "Payload",
            "Flamingo",
            "Flagrant",
            "Kenny G",
            "Dust Bowl",
            "Tugboat",
            "Craw Daddy",
            "Thighs",
            "Baby Ruth",
            "SandMan",
            "Triple Jump",
            "Cutler",
            "Minnow",
            "8 Bit",
            "Miranda",
            "One Tree Hill",
            "Boo Boo",
            "Tonka",
            "Rebel (2.0)",
            "Life Alert",
            "SeaChicken",
            "Barn Door",
            "Ice Bomb",
            "Knee-chi",
            "Well Flower",
            "Peg",
            "WarmUp",
            "NotYet",
            "HiYa (2.0)",
            "W",
            "Pop",
            "Mayflower",
            "Bombs",
            "Coleman",
            "Grunt",
            "Pyro",
            "Frank The Tank",
            "Kathy",
            "Knobby",
            "Smokey",
            "Cherry",
            "Marsha Marsha",
            "Yanni",
            "Astro-Pop",
            "Wrangler",
            "Slug",
            "Dead End",
            "WoodChip",
            "Squirt",
            "Punky Brewster",
            "Juicy Fruit",
            "Watt",
            "BigGulp",
            "Doodles",
            "Texas Ranger",
            "Gift Wrap",
            "Jet Lag",
            "Fumble",
            "Roxbury",
            "Sailor Moon",
            "Slipknot",
            "Turtleneck",
            "Chopped Chilis",
            "Origami",
            "Hillbilly",
            "Messi (2.0)",
            "Joe Dirt",
            "Cricket",
            "Dunder",
            "Second Hand",
            "Nail'd It",
            "Rubber Neck",
            "SweatShop",
            "ShamWOW!",
            "Terry Cloth",
            "Funnel Cake",
            "Mid-Range",
            "ATF",
            "Extra Crispy",
            "U Rang",
            "Teleport",
            "Arigato",
            "Cheerio",
            "Closer",
            "Once",
            "Sideswipe",
            "Diaper Gene",
            "Gutter Ball",
            "Swirley",
            "Charlie Horse",
            "Toasty",
            "Pyle",
            "Jackpot",
            "Sunkist",
            "Beaker",
            "Baby Blue",
            "Shenanigans",
            "Bellhop",
            "Vanilla Ice",
            "Kick-Stand",
            "Cheesesteak",
            "Taco Tuesday",
            "Herbie",
            "Matinee",
            "Scooter",
            "Redo",
            "Oh Snap!",
            "Deep Blue (2.0)",
            "Sprinkles (2.0)",
            "Brains",
            "Riddler",
            "Cinderella",
            "Wattles",
            "The View",
            "Deep Dish",
            "TBone",
            "Surf&Turf",
            "ChinaShop (2.0)",
            "Platter",
            "Mac-N-Cheese (2.0)",
            "RoadRash (2.0)",
            "Growing Pains (2.0)",
            "No Show",
            "Peacock",
            "Tom Shane",
            "Cover-Up (2.0)",
            "Pixel (2.0)",
            "RamRod (2.0)",
            "Daffodil",
            "Steelcut (2.0)",
            "Karl",
            "Rousey",
            "Glitch (2.0)",
            "Bull Jingle",
            "All In",
            "XPort",
            "Midnight Madness",
            "One Time",
            "Mr. No Name (2.0)",
            "Wedding Cake",
            "Cart Narc",
            "Pink Panther",
            "Twinkle Toes",
            "Floppy Disk",
            "Etsy",
            "Bonnet",
            "Accidentally (2.0)",
            "Kinky Boots",
            "Snow White",
            "Shipwreck",
            "Bubbles",
            "Brady Bunch",
            "ThreePete",
            "PawPatrol",
            "Yogi",
            "Woody",
            "Switch",
            "Richard Simmons ",
            "Unicorn",
            "Geico",
            "Uke",
            "Chicken Wing (2.0)",
            "That Guy",
            "Sixth Sense",
            "Tingles",
            "Mysterio",
            "Milan",
            "Aflac",
            "Bugz (2.0)",
            "Wanda",
            "Hermione",
            "Montana",
            "Last Night",
            "Rollover",
            "Spring Break",
            "In-N-Out",
            "Citation",
            "Special Ed",
            "Cyclops",
            "Flanders",
            "Slug Bug",
            "Moped",
            "Carpool",
            "Mr.Wilson",
            "Rocket (2.0)",
            "Ghost (2.0)",
            "Mermaid",
            "The Rack",
            "Nemo",
            "Fran",
            "Mr. Piranha (2.0)",
            "Overboard",
            "Redfin",
            "Blart",
            "FishNet",
            "Popfly (2.0)",
            "MapQuest",
            "GardenNomad",
            "Noodle (D.0.G)",
            "Travolta",
            "Twinkie",
            "Nuge",
            "Soft Serve",
            "Macchiato",
            "Stumblina",
            "BlackBeauty",
            "Counterfeit",
            "Stepside",
            "Looney Tunes",
            "Dirtbag",
            "Reversal",
            "Roomba",
            "Stretch",
            "Forty-Three",
            "Tea Bag",
            "Paper Trail",
            "Fine Dining",
            "Gizmo (2.0)",
            "Goonie (2.0)",
            "Paddywagon (2.0)",
            "LaBeouf",
            "Mud Bath",
            "DC Talk",
            "Decoy",
            "Shred",
            "Belle",
            "Hot Yoga",
            "Hot Wax",
            "cheech",
            "Enchirito",
            "Ed",
            "Face Plant (2.0)",
            "Rio",
            "Double Play",
            "Wish Bone",
            "Focus (2.0)",
            "Cap'n Hook",
            "Bugz (2.0)",
            "Ralph",
            "Jackelope",
            "Popcorn (2.0)",
            "Kung Fu Panda",
            "Patty^2"
        };
    }
}